name: AIGID_baseline
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch=2.6.0
  - torchvision=0.21.0
  - pytorch-cuda=12.4
  - pip
  - pip:
    - kornia>=0.8.0
    - numpy<2
    - pandas>=2.0
    - pillow>=10.0
    - pytorch-lightning>=2.5.0
    - torchmetrics>=1.0
    - scipy>=1.10
    - timm>=1.0.0
    - rich
    - pyyaml
    - tqdm
